/**
 * Chinese translations for skills and tags.
 *
 * Skill translations are stored in a standalone JSON file
 * (skill-translations-zh.json) generated by scripts/generate-skill-translations.mjs.
 * Tags use an inline map for the most common catalog tags.
 */
import skillTranslationsZh from "./skill-translations-zh.json";

type SkillTranslation = {
  name: string;
  description: string;
};

const typedTranslations = skillTranslationsZh as Record<
  string,
  SkillTranslation
>;

/**
 * Chinese translations for common skill tags.
 * Tags not in this map are displayed as-is.
 */
const tagTranslationsZh: Record<string, string> = {
  latest: "最新",
  automation: "自动化",
  ai: "AI",
  finance: "金融",
  security: "安全",
  api: "API",
  crypto: "加密货币",
  mcp: "MCP",
  openclaw: "OpenClaw",
  memory: "记忆",
  productivity: "效率",
  agents: "智能体",
  audit: "审计",
  compliance: "合规",
  agent: "智能体",
  business: "商业",
  defi: "DeFi",
  base: "基础",
  blockchain: "区块链",
  chinese: "中文",
  marketing: "营销",
  "ai-agents": "AI 智能体",
  content: "内容",
  research: "研究",
  monitoring: "监控",
  search: "搜索",
  safety: "安全",
  cli: "命令行",
  devops: "运维",
  documentation: "文档",
  email: "邮件",
  operations: "运营",
  trading: "交易",
  analysis: "分析",
  "social-media": "社交媒体",
  "ai-agent": "AI 智能体",
  browser: "浏览器",
  identity: "身份",
  "multi-agent": "多智能体",
  governance: "治理",
  context: "上下文",
  solana: "Solana",
  health: "健康",
  hr: "人力资源",
  social: "社交",
  github: "GitHub",
  sales: "销售",
  analytics: "数据分析",
  bitcoin: "比特币",
  workflow: "工作流",
  tools: "工具",
  code: "代码",
  data: "数据",
  database: "数据库",
  design: "设计",
  development: "开发",
  education: "教育",
  entertainment: "娱乐",
  file: "文件",
  gaming: "游戏",
  image: "图片",
  language: "语言",
  legal: "法律",
  math: "数学",
  media: "媒体",
  music: "音乐",
  network: "网络",
  news: "新闻",
  payment: "支付",
  project: "项目",
  science: "科学",
  server: "服务器",
  storage: "存储",
  testing: "测试",
  text: "文本",
  translation: "翻译",
  utility: "工具",
  video: "视频",
  weather: "天气",
  web: "网页",
  writing: "写作",
  calendar: "日历",
  chat: "聊天",
  cloud: "云",
  communication: "通讯",
  "customer-support": "客服",
  ecommerce: "电商",
  kubernetes: "Kubernetes",
  docker: "Docker",
  slack: "Slack",
  discord: "Discord",
  telegram: "Telegram",
  twitter: "Twitter",
  notion: "Notion",
  "real-estate": "房地产",
  travel: "旅行",
  food: "美食",
  fitness: "健身",
  crypto_trading: "加密货币交易",
  ethereum: "以太坊",
  nft: "NFT",
  web3: "Web3",
  dao: "DAO",
  llm: "大模型",
  rag: "RAG",
  embedding: "向量嵌入",
  prompt: "提示词",
  "machine-learning": "机器学习",
};

/**
 * Returns the localized tag label, falling back to the original.
 */
export function getTagLabel(tag: string, locale: string): string {
  if (locale !== "zh") return tag;
  return tagTranslationsZh[tag] ?? tag;
}

/**
 * Returns the localized name for a skill, falling back to the original.
 */
export function getSkillName(
  slug: string,
  originalName: string,
  locale: string,
): string {
  if (locale !== "zh") return originalName;
  return typedTranslations[slug]?.name ?? originalName;
}

/**
 * Returns the localized description for a skill, falling back to the original.
 */
export function getSkillDescription(
  slug: string,
  originalDescription: string,
  locale: string,
): string {
  if (locale !== "zh") return originalDescription;
  return typedTranslations[slug]?.description ?? originalDescription;
}

/**
 * Returns the text fields that should participate in search for the current
 * locale while preserving source English matches.
 */
export function getSkillSearchText(
  slug: string,
  originalName: string,
  originalDescription: string,
  locale: string,
): string {
  const localizedName = getSkillName(slug, originalName, locale);
  const localizedDescription = getSkillDescription(
    slug,
    originalDescription,
    locale,
  );

  return [
    slug,
    originalName,
    originalDescription,
    localizedName,
    localizedDescription,
  ]
    .join("\n")
    .toLowerCase();
}
